# ===================================
#  Relation Behavior Config
# ===================================
todo:
    label: Todo
    list: @/plugins/shahiemseymor/todo/models/todo/columns.yaml
    form: @/plugins/shahiemseymor/todo/models/todo/fields.yaml
    emptyMessage: backend::lang.list.no_records